apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager
  labels:
    app: taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: dmdeepak/taskmanager:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://admin:password@mongodb-service:27017/test?authSource=admin
