apiVersion: v1
kind: Service
metadata:
  name: taskmanager-service
  labels:
    app: taskmanager
spec:
  selector:
    app: taskmanager
  ports:
    - protocol: TCP
      port: 80         # External port for clients
      targetPort: 8080 # Container port your app listens on
  type: LoadBalancer  # Use LoadBalancer if your cluster supports it; else use NodePort or ClusterIP
